{
 "title": "PostgreSQL dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "DRIVERS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Drivers",
   "type": "gauge",
   "description": "How many do we have? 😜",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS total_drivers\nFROM employees\nWHERE role = 'driver';"
    }
   ]
  },
  {
   "title": "Drivers with Vehicles",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT e.id) AS drivers_with_vehicles\nFROM employees e\nJOIN vehicle_employee ve ON e.id = ve.employee_id\nWHERE e.role = 'driver'\n  AND ve.since_date <= CURRENT_DATE\n  AND (ve.planned_leave_date IS NULL OR ve.planned_leave_date > CURRENT_DATE);"
    }
   ]
  },
  {
   "title": "Drivers without Vehicles",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS drivers_without_vehicles\nFROM employees e\nWHERE role = 'driver'\n  AND NOT EXISTS (\n    SELECT 1\n    FROM vehicle_employee ve\n    WHERE ve.employee_id = e.id\n      AND ve.since_date <= CURRENT_DATE\n      AND (ve.planned_leave_date IS NULL OR ve.planned_leave_date > CURRENT_DATE)\n  );\n"
    }
   ]
  },
  {
   "title": "Drivers Currently Using a Vehicle",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n    e.id AS driver_id,\n    e.name AS driver_name,\n    v.license_plate AS vehicle,\n    ve.since_date AS assigned_since,\n    ve.planned_leave_date AS assigned_until\nFROM\n    employees e\nJOIN vehicle_employee ve\n    ON e.id = ve.employee_id\nJOIN vehicles v\n    ON ve.vehicle_id = v.id\nWHERE\n    e.role = 'driver'\n    AND ve.since_date <= CURRENT_DATE\n    AND (ve.planned_leave_date IS NULL OR ve.planned_leave_date > CURRENT_DATE)\nORDER BY\n    e.name, ve.since_date;\n"
    }
   ]
  },
  {
   "title": "Drivers without a vehicle",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n    e.id AS driver_id,\n    e.name AS driver_name\nFROM\n    employees e\nWHERE\n    e.role = 'driver'\n    AND NOT EXISTS (\n        SELECT 1\n        FROM vehicle_employee ve\n        WHERE\n            ve.employee_id = e.id\n            AND ve.since_date <= CURRENT_DATE\n            AND (ve.planned_leave_date IS NULL OR ve.planned_leave_date > CURRENT_DATE)\n    )\nORDER BY\n    e.name;\n"
    }
   ]
  }
 ]
}