import { generateRandomPolishRegistration } from "./vehicle-registration.mocks";
import { Truck } from "./vehicles.model";

export const mockTrucks: Truck[] = [
  { id: 'TR001', model: 'Volvo FH16', driver: 'Michał Kowalski', status: 'On Route', capacity: '40 ton', location: 'Mazowieckie' },
  { id: 'TR002', model: 'Mercedes Actros', driver: 'Anna Nowak', status: 'Available', capacity: '38 ton', location: 'Małopolskie' },
  { id: 'TR003', model: 'Scania R450', driver: 'Piotr Wiśniewski', status: 'Maintenance', capacity: '42 ton', location: 'Wielkopolskie' },
  { id: 'TR004', model: 'MAN TGX', driver: 'Magdalena Dąbrowska', status: 'On Route', capacity: '36 ton', location: 'Dolnośląskie' },
  { id: 'TR005', model: 'DAF XF', driver: 'Jakub Lewandowski', status: 'Available', capacity: '44 ton', location: 'Śląskie' },
  { id: 'TR006', model: 'Iveco Stralis', driver: 'Katarzyna Zielińska', status: 'On Route', capacity: '40 ton', location: 'Pomorskie' },
  { id: 'TR007', model: 'Renault T High', driver: 'Tomasz Szymański', status: 'Available', capacity: '35 ton', location: 'Łódzkie' },
  { id: 'TR008', model: 'Volvo FH', driver: 'Monika Woźniak', status: 'On Route', capacity: '41 ton', location: 'Lubelskie' },
  { id: 'TR009', model: 'Scania S500', driver: 'Marcin Kozłowski', status: 'Maintenance', capacity: '39 ton', location: 'Kujawsko-pomorskie' },
  { id: 'TR010', model: 'Mercedes Arocs', driver: 'Agnieszka Jankowska', status: 'On Route', capacity: '40 ton', location: 'Zachodniopomorskie' },
  { id: 'TR011', model: 'MAN TGS', driver: 'Paweł Mazur', status: 'Available', capacity: '43 ton', location: 'Warmińsko-mazurskie' },
  { id: 'TR012', model: 'DAF CF', driver: 'Beata Krawczyk', status: 'Maintenance', capacity: '37 ton', location: 'Podlaskie' },
  { id: 'TR013', model: 'Volvo FH13', driver: 'Łukasz Grabowski', status: 'On Route', capacity: '38 ton', location: 'Podkarpackie' },
  { id: 'TR014', model: 'Scania R500', driver: 'Ewa Baran', status: 'Available', capacity: '41 ton', location: 'Lubuskie' },
  { id: 'TR015', model: 'Mercedes Actros', driver: 'Grzegorz Pawlak', status: 'Maintenance', capacity: '40 ton', location: 'Opolskie' },
  { id: 'TR016', model: 'Iveco S-Way', driver: 'Patryk Górski', status: 'On Route', capacity: '39 ton', location: 'Świętokrzyskie' },
  { id: 'TR017', model: 'DAF XF 480', driver: 'Barbara Król', status: 'Available', capacity: '44 ton', location: 'Mazowieckie' },
  { id: 'TR018', model: 'MAN TGX', driver: 'Rafał Czarnecki', status: 'On Route', capacity: '42 ton', location: 'Małopolskie' },
  { id: 'TR019', model: 'Renault T', driver: 'Karolina Wójcik', status: 'Maintenance', capacity: '37 ton', location: 'Wielkopolskie' },
  { id: 'TR020', model: 'Scania S730', driver: 'Marek Nowicki', status: 'Available', capacity: '45 ton', location: 'Dolnośląskie' },
  { id: 'TR021', model: 'Volvo FH16', driver: 'Natalia Sikora', status: 'On Route', capacity: '40 ton', location: 'Śląskie' },
  { id: 'TR022', model: 'Mercedes Arocs', driver: 'Artur Dudek', status: 'Available', capacity: '38 ton', location: 'Pomorskie' },
  { id: 'TR023', model: 'DAF CF', driver: 'Joanna Rutkowska', status: 'On Route', capacity: '41 ton', location: 'Łódzkie' },
  { id: 'TR024', model: 'Iveco Stralis', driver: 'Adrian Piotrowski', status: 'Maintenance', capacity: '36 ton', location: 'Lubelskie' },
  { id: 'TR025', model: 'MAN TGS', driver: 'Dorota Malinowska', status: 'Available', capacity: '43 ton', location: 'Kujawsko-pomorskie' },
  { id: 'TR026', model: 'Renault T High', driver: 'Sebastian Lis', status: 'On Route', capacity: '39 ton', location: 'Zachodniopomorskie' },
  { id: 'TR027', model: 'Scania R410', driver: 'Aleksandra Pawłowska', status: 'Available', capacity: '37 ton', location: 'Warmińsko-mazurskie' },
  { id: 'TR028', model: 'Volvo FH', driver: 'Mariusz Sadowski', status: 'Maintenance', capacity: '44 ton', location: 'Podlaskie' },
  { id: 'TR029', model: 'Mercedes Actros', driver: 'Kinga Zawadzka', status: 'On Route', capacity: '40 ton', location: 'Podkarpackie' },
  { id: 'TR030', model: 'DAF XF', driver: 'Tadeusz Bąk', status: 'Available', capacity: '42 ton', location: 'Lubuskie' },
  { id: 'TR031', model: 'MAN TGX', driver: 'Izabela Sokołowska', status: 'Maintenance', capacity: '38 ton', location: 'Opolskie' },
  { id: 'TR032', model: 'Iveco S-Way', driver: 'Andrzej Sawicki', status: 'On Route', capacity: '41 ton', location: 'Świętokrzyskie' },
  { id: 'TR033', model: 'Renault T', driver: 'Paulina Michalska', status: 'Available', capacity: '36 ton', location: 'Mazowieckie' },
  { id: 'TR034', model: 'Scania S500', driver: 'Wojciech Tomaszewski', status: 'On Route', capacity: '45 ton', location: 'Małopolskie' },
  { id: 'TR035', model: 'Volvo FH16', driver: 'Zuzanna Kaczmarek', status: 'Maintenance', capacity: '40 ton', location: 'Wielkopolskie' },
  { id: 'TR036', model: 'Mercedes Arocs', driver: 'Przemysław Jasiński', status: 'Available', capacity: '39 ton', location: 'Dolnośląskie' },
  { id: 'TR037', model: 'DAF CF', driver: 'Renata Marciniak', status: 'On Route', capacity: '43 ton', location: 'Śląskie' },
  { id: 'TR038', model: 'Iveco Stralis', driver: 'Damian Kalinowski', status: 'Available', capacity: '41 ton', location: 'Pomorskie' },
  { id: 'TR039', model: 'MAN TGS', driver: 'Elżbieta Sobczak', status: 'Maintenance', capacity: '37 ton', location: 'Łódzkie' },
  { id: 'TR040', model: 'Renault T High', driver: 'Filip Chmielewski', status: 'On Route', capacity: '44 ton', location: 'Lubelskie' },
  { id: 'TR041', model: 'Scania R450', driver: 'Jolanta Urban', status: 'Available', capacity: '38 ton', location: 'Kujawsko-pomorskie' },
  { id: 'TR042', model: 'Volvo FH', driver: 'Kamil Walczak', status: 'On Route', capacity: '40 ton', location: 'Zachodniopomorskie' },
  { id: 'TR043', model: 'Mercedes Actros', driver: 'Marek Kowalczyk', status: 'Available', capacity: '39 ton', location: 'Podlaskie' },
  { id: 'TR044', model: 'DAF XF 480', driver: 'Piotr Nowicki', status: 'On Route', capacity: '43 ton', location: 'Podkarpackie' },
  { id: 'TR045', model: 'MAN TGX', driver: 'Bartosz Zawadzki', status: 'Maintenance', capacity: '37 ton', location: 'Lubuskie' },
  { id: 'TR046', model: 'Renault T', driver: 'Michał Kowalski', status: 'On Route', capacity: '44 ton', location: 'Opolskie' },
  { id: 'TR047', model: 'Scania S730', driver: 'Piotr Wiśniewski', status: 'Available', capacity: '40 ton', location: 'Świętokrzyskie' },
  { id: 'TR048', model: 'Volvo FH16', driver: 'Adam Nowak', status: 'On Route', capacity: '42 ton', location: 'Mazowieckie' },
  { id: 'TR049', model: 'Mercedes Arocs', driver: 'Kamil Zieliński', status: 'Available', capacity: '38 ton', location: 'Małopolskie' },
  { id: 'TR050', model: 'DAF CF', driver: 'Michał Dąbrowski', status: 'On Route', capacity: '41 ton', location: 'Wielkopolskie' },
  { id: 'TR051', model: 'Iveco Stralis', driver: 'Katarzyna Zielińska', status: 'Available', capacity: '44 ton', location: 'Pomorskie' },
  { id: 'TR052', model: 'MAN TGS', driver: 'Tomasz Szymański', status: 'On Route', capacity: '39 ton', location: 'Łódzkie' },
  { id: 'TR053', model: 'Renault T High', driver: 'Monika Woźniak', status: 'Maintenance', capacity: '37 ton', location: 'Kujawsko-pomorskie' },
  { id: 'TR054', model: 'Scania R410', driver: 'Marcin Kozłowski', status: 'On Route', capacity: '40 ton', location: 'Zachodniopomorskie' },
  { id: 'TR055', model: 'Volvo FH', driver: 'Agnieszka Jankowska', status: 'Available', capacity: '42 ton', location: 'Warmińsko-mazurskie' },
  { id: 'TR056', model: 'Mercedes Actros', driver: 'Paweł Mazur', status: 'On Route', capacity: '38 ton', location: 'Podlaskie' },
];

for (const truck of mockTrucks) {
  truck.id = generateRandomPolishRegistration();
}
