DATA_QUANTITIES = {
    "NUM_LOCATIONS": 3,
    "NUM_WAREHOUSES": 3,
    "NUM_ZONES": 5,
    "NUM_AISLES": 7,
    "NUM_RACKS": 10,
    "NUM_SHELVES": 15,
    "NUM_CUSTOMERS": 50,
    "NUM_EMPLOYEES": 20,
    "NUM_STORAGE_REQUESTS": 200,
    "NUM_STORAGE_RECORDS": 4,
    "NUM_PAYMENTS": 40,
    "NUM_CARGO_EVENT_HISTORY": 4
}
