FROM node:23.11.0-alpine3.21

RUN addgroup -S 1000 && adduser -S 1000 -G 1000
WORKDIR /app

ARG DATABASE_URL

ENV DATABASE_URL=${DATABASE_URL}

USER 1000:1000

COPY --chown=1000:1000 /prisma ./prisma

CMD ["npx", "prisma", "migrate", "deploy", "--schema=./prisma/schema.prisma"]
