FROM node:23.11.0-alpine3.21

RUN addgroup -S 1000 && adduser -S 1000 -G 1000
WORKDIR /app

RUN npm install ts-node @types/node typescript @prisma/client bcryptjs

ARG DATABASE_URL

ENV DATABASE_URL=${DATABASE_URL}

RUN mkdir -p /app/node_modules/.prisma \
  && chown -R 1000:1000 /app/node_modules

USER 1000:1000

COPY --chown=1000:1000 . .
COPY --chown=1000:1000 /prisma ./prisma

RUN npx prisma generate

COPY --chown=1000:1000 /migrate-and-seed.sh ./migrate-and-seed.sh
RUN chmod +x ./migrate-and-seed.sh

CMD ["npx", "prisma", "migrate", "deploy", "--schema=./prisma/schema.prisma"]
